### ISSUE TITLE
Broken on boot2docker 1.9.1

### ISSUE THREAD

**Issue by pklingem** [Mashape/docker-cassandra#3]
I'm unable to get this image running inside boot2docker 1.9.1, however it runs fine on boot2docker 1.9.0.  Not sure how best to troubleshoot, but I'd be glad to provide any information that might help resolve the issue.

I do see the following in the machine:

![image](https://cloud.githubusercontent.com/assets/46536/11509035/cc3cedd8-9829-11e5-8acf-1ca9e35f62f4.png)

**Comment by zhangcheng** [comment]
It happened to me as well. I didn't try 1.9.0, instead, I reverted back to 1.8.3.

https://github.com/docker/docker/issues/17720#issuecomment-159440563
